<?php

$graphite_data = array (
       array("name" => "MWIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.modernwar.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "CCIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.crimecity.server_errors.total&format=json&from=-4hours", "stat" =>""),
//       array("name" => "DRIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.dragonia.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "KAIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.kingdomage.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "MAIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.monsterage.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "NFLIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.neptune.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "SWIOS", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.ios.slotzio.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "SWAND", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.android.slotzio.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "CCAND", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.android.crimecity.server_errors.total&format=json&from=-4hours", "stat" =>""),
       array("name" => "MWAND", "url" => "http://graphite-master.int.funzio.com/render?target=1_Minute.android.modernwar.server_errors.total&format=json&from=-4hours", "stat" =>"")
)

?>
